### ISSUE TITLE
Simultaneous dial between two swarms causes timeout on both ends

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p-swarm#15] opened 2017-01-23 19:14 UTC
Log excerpt:

```
19:58:43.513 DEBUG     swarm2: Swarm: NewStreamWithPeer no connections. Attempting to connect... swarm.go:277
19:58:43.513 DEBUG     swarm2: Swarm: NewStreamWithPeer no connections. Attempting to connect... swarm.go:277
19:58:43.513 DEBUG     swarm2: <peer.ID Y7FcUm> swarm dialing <peer.ID Uo39bQ> %!s(<-chan multiaddr.Multiaddr=0xc4203196e0) swarm_dial.go:288
19:58:43.513 DEBUG     swarm2: <peer.ID Uo39bQ> swarm dialing <peer.ID Y7FcUm> %!s(<-chan multiaddr.Multiaddr=0xc4203b0ae0) swarm_dial.go:288
19:58:43.513 DEBUG     swarm2: <peer.ID Y7FcUm> swarm dialing <peer.ID Uo39bQ> /ip4/127.0.0.1/tcp/20001 swarm_dial.go:348
19:58:43.513 DEBUG     swarm2: <peer.ID Uo39bQ> swarm dialing <peer.ID Y7FcUm> /ip4/127.0.0.1/tcp/20002 swarm_dial.go:348
```

Leads to:

```
19:58:53.513 DEBUG     swarm2: dial end <nil> swarm_dial.go:204
19:58:53.513 DEBUG     swarm2: dial end <nil> swarm_dial.go:204
19:58:53.513 ERROR    cluster: <peer.ID Y7FcUm>: error in broadcast response from <peer.ID Uo39bQ>: dial attempt failed: context deadline exceeded  cluster.go:482
19:58:53.513 ERROR    cluster: <peer.ID Uo39bQ>: error in broadcast response from <peer.ID Y7FcUm>: dial attempt failed: context deadline exceeded  cluster.go:482
```

I see it mostly during testing, when running swarms in parallel. Some tests would randomly fail because of it. Other times dialing works just fine (probably depending on timings).

Also, any subsequent retries are greeted by a backoff.

**Comment by Stebalien** [comment] 2018-01-23 03:04
The problem is TCP's simultaneous open feature: https://github.com/libp2p/go-tcp-transport/issues/21

**Comment by marten-seemann** [comment] 2022-05-25 19:27
This should be fixed by the Simultaneous Open multistream extension.

**Closed by marten-seemann** 2022-05-25 19:27 UTC
